{"sections":[],"metadata":{"modules":[{"name":"LiveViewNativeCore"}],"role":"symbol","title":"SocketShutdownError.AlreadyJoined","symbolKind":"case","roleHeading":"Case","externalID":"s:18LiveViewNativeCore19SocketShutdownErrorO13AlreadyJoinedyA2CmF","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlreadyJoined"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore\/SocketShutdownError\/AlreadyJoined"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"AlreadyJoined","kind":"identifier"}],"platforms":["macOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The async task was already joined by another call, so the [Result] or panic from the async"},{"text":" ","type":"text"},{"type":"text","text":"task can’t be reported here."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/liveviewnativecore\/socketshutdownerror\/alreadyjoined"]}],"hierarchy":{"paths":[["doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore","doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore\/SocketShutdownError"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://liveview-native-core.LiveViewNativeCore/documentation/LiveViewNativeCore":{"title":"LiveViewNativeCore","kind":"symbol","url":"\/documentation\/liveviewnativecore","type":"topic","role":"collection","identifier":"doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore","abstract":[]},"doc://liveview-native-core.LiveViewNativeCore/documentation/LiveViewNativeCore/SocketShutdownError/AlreadyJoined":{"role":"symbol","url":"\/documentation\/liveviewnativecore\/socketshutdownerror\/alreadyjoined","title":"SocketShutdownError.AlreadyJoined","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlreadyJoined","kind":"identifier"}],"abstract":[{"text":"The async task was already joined by another call, so the [Result] or panic from the async","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"task can’t be reported here."}],"identifier":"doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore\/SocketShutdownError\/AlreadyJoined","kind":"symbol","type":"topic"},"doc://liveview-native-core.LiveViewNativeCore/documentation/LiveViewNativeCore/SocketShutdownError":{"kind":"symbol","abstract":[{"type":"text","text":"Error from [Socket::shutdown] or from the server itself that caused the [Socket] to shutdown."}],"title":"SocketShutdownError","url":"\/documentation\/liveviewnativecore\/socketshutdownerror","navigatorTitle":[{"text":"SocketShutdownError","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocketShutdownError"}],"identifier":"doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore\/SocketShutdownError","type":"topic","role":"symbol"}}}